assembler-2 0 1 recipe:green-circuit
inserter-fast 1 -1 :south
inserter-fast 1 3 :south
belt-blue 0 -2 :east
belt-blue 1 -2 :east
belt-blue 2 -2 :east
belt-blue 3 -2 :east
belt-blue 4 -2 :east
belt-blue 0 4 :east
belt-blue 1 4 :east
belt-blue 2 4 :east
belt-blue 3 4 :east
belt-blue 4 4 :east